import type { SystemLog } from '@/types';
import { daysAgo } from '@/utils/date';

export const mockSystemLogs: SystemLog[] = [
  { id: 'sl1', timestamp: daysAgo(0), level: 'INFO', module: 'Authentication', message: 'User u3 logged in successfully.' },
  { id: 'sl2', timestamp: daysAgo(0), level: 'INFO', module: 'Attendance', message: 'QR scan recorded time-in for user u8.' },
  { id: 'sl3', timestamp: daysAgo(1), level: 'WARNING', module: 'Borrowing', message: 'Borrowing bw5 flagged as overdue by scheduled job.' },
  { id: 'sl4', timestamp: daysAgo(1), level: 'INFO', module: 'Requests', message: 'Request req1 created by user u3.' },
  { id: 'sl5', timestamp: daysAgo(2), level: 'ERROR', module: 'File Upload', message: 'Simulated ID upload exceeded the 5MB mock size limit for user u6.' },
  { id: 'sl6', timestamp: daysAgo(2), level: 'INFO', module: 'Notifications', message: 'Due-date reminder queued for borrowing bw1.' },
  { id: 'sl7', timestamp: daysAgo(3), level: 'WARNING', module: 'Inventory', message: 'Book b15 has zero available copies with 1 active reservation.' },
  { id: 'sl8', timestamp: daysAgo(4), level: 'INFO', module: 'Reports', message: 'Borrowing Trends report generated by user u2.' },
  { id: 'sl9', timestamp: daysAgo(5), level: 'INFO', module: 'Authentication', message: 'Password reset link requested for admin@library.test (mock).' },
  { id: 'sl10', timestamp: daysAgo(7), level: 'INFO', module: 'Backup & Restore', message: 'Manual backup completed successfully (412 MB).' },
  { id: 'sl11', timestamp: daysAgo(9), level: 'INFO', module: 'Announcements', message: 'Announcement ann1 published by user u2.' },
  { id: 'sl12', timestamp: daysAgo(14), level: 'WARNING', module: 'Requests', message: 'Borrowing request req4 rejected — no available copies.' },
  { id: 'sl13', timestamp: daysAgo(30), level: 'ERROR', module: 'Database', message: 'Simulated connection timeout while syncing catalog cache (auto-recovered).' },
  { id: 'sl14', timestamp: daysAgo(35), level: 'WARNING', module: 'User Management', message: 'User u7 suspended after 3 consecutive overdue returns.' },
  { id: 'sl15', timestamp: daysAgo(60), level: 'INFO', module: 'Recycle Bin', message: 'Book record restored from recycle bin by user u1.' },
];
